package gui;

import classes.CustomerInformation;
import java.util.Iterator;
import javax.swing.ImageIcon;

public class EditCustUI extends javax.swing.JFrame {

    private String custID = "";
    private int counterNumber = 0;
    private String framecustEditTitle = "";

    /**
     * Creates new form EditCustUI
     */
    public EditCustUI(int counterNumber, String custID) {
        this.custID = custID;
        this.counterNumber = counterNumber;
        this.framecustEditTitle = "Customer " + custID;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        editcusttitle.setText("Edit customer " + custID);
        pack();
        setLocationRelativeTo(null);
        
        //GET OLD CUST DATA AND DISPLAY TO UI
        String custName = "";
        String custIC = "";
        
        if (counterNumber == 1) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter1().iterator(); iterator.hasNext();) {
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUST DATA
                    custName = nextCustData.getCustName();
                    custIC = nextCustData.getCustIC();
                    break;
                }
            }
        } else if (counterNumber == 2) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter2().iterator(); iterator.hasNext();) {
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUST DATA
                    custName = nextCustData.getCustName();
                    custIC = nextCustData.getCustIC();
                    break;
                }
            }
        } else if (counterNumber == 3) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter3().iterator(); iterator.hasNext();) {
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUST DATA
                    custName = nextCustData.getCustName();
                    custIC = nextCustData.getCustIC();
                    break;
                }
            }
        }
        
        custnamefield.setText(custName);
        custicfield.setText(custIC);
    }
    
    ImageIcon logo = new ImageIcon("src/images/mainicon.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        editcusttitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        custnamefield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        custicfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(framecustEditTitle);
        setIconImage(logo.getImage());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        editcusttitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        editcusttitle.setText("Edit customer -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editcusttitle)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editcusttitle)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setText("Customer name:");

        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jLabel2.setText("Customer IC:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custnamefield)
                            .addComponent(custicfield))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(custicfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        //SAVE EDITED ITEM HERE
        String custName = custnamefield.getText();
        String custIC = custicfield.getText();

        int index = 0;
        if (counterNumber == 1) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter1().iterator(); iterator.hasNext();) {
                index++;
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUSTOMER DATA
                    String counterPaid = nextCustData.getCounterPaid();
                    String itemID = nextCustData.getItemID();
                    String itemName = nextCustData.getItemName();
                    double itemPrice = nextCustData.getitemPrice();
                    String datePurchased = nextCustData.getDatePurchase();

                    bahagiamall.BahagiaMall.getCounter1().set(index - 1, new CustomerInformation(custID, custIC, custName, counterPaid, itemID, itemName, itemPrice, datePurchased));
                }
            }
        } else if (counterNumber == 2) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter2().iterator(); iterator.hasNext();) {
                index++;
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUSTOMER DATA
                    String counterPaid = nextCustData.getCounterPaid();
                    String itemID = nextCustData.getItemID();
                    String itemName = nextCustData.getItemName();
                    double itemPrice = nextCustData.getitemPrice();
                    String datePurchased = nextCustData.getDatePurchase();

                    bahagiamall.BahagiaMall.getCounter2().set(index - 1, new CustomerInformation(custID, custIC, custName, counterPaid, itemID, itemName, itemPrice, datePurchased));
                }
            }
        } else if (counterNumber == 3) {
            for (Iterator iterator = bahagiamall.BahagiaMall.getCounter3().iterator(); iterator.hasNext();) {
                index++;
                CustomerInformation nextCustData = (CustomerInformation) iterator.next();
                if (nextCustData.getCustID().equalsIgnoreCase(custID)) {
                    //GET OLD CUSTOMER DATA
                    String counterPaid = nextCustData.getCounterPaid();
                    String itemID = nextCustData.getItemID();
                    String itemName = nextCustData.getItemName();
                    double itemPrice = nextCustData.getitemPrice();
                    String datePurchased = nextCustData.getDatePurchase();

                    bahagiamall.BahagiaMall.getCounter3().set(index - 1, new CustomerInformation(custID, custIC, custName, counterPaid, itemID, itemName, itemPrice, datePurchased));
                }
            }
        }
        dispose();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        //CANCEL
        dispose();
    }//GEN-LAST:event_jButton2MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custicfield;
    private javax.swing.JTextField custnamefield;
    private javax.swing.JLabel editcusttitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
